### ISSUE TITLE
Logging Module

### ISSUE THREAD

**Issue by dyaneshvarun** [arkn98/adeia-api#2]
Choose the right library for Logging / Build one for managing different logging levels : DEBUG/INFO/ WARN/ ERROR/

**Comment by arkn98** [comment]
[zap](https://github.com/uber-go/zap), from Uber, seems like a solid option for our use-case.

**Comment by dyaneshvarun** [comment]
Seems that logrus is outshadowing others here as well. 

Having said that , I am okey with anything that provides me 
`LOGGER.info(Object)`
`LOGGER.debug(Object)`
`LOGGER.error(Object)` 
by any means. Happy to adopt to any of the styles.
